# Numpy


*    Extension package to Python for multi-dimensional arrays
*    Closer to hardware (efficiency)
*    Designed for scientific computation (convenience)
*    Also known as array oriented computing

[More about arrays](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

## Basic information

In [4]:
a.shape

(4,)

In [5]:
a.dtype

dtype('int64')

In [22]:
a.ndim

1

In [6]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

## Operations

Operations over arrays are elementwise and fast

In [7]:
a = np.arange(1000)

In [8]:
L = range(1000)

In [9]:
%timeit [i**2 for i in L]

191 µs ± 2.44 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
%timeit a**2

993 ns ± 1.25 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
%timeit sum(L)

11.4 µs ± 3.12 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
%timeit np.sum(a)

2.37 µs ± 6.38 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
np.array?

## >1d `nparray`

`nparrays` can have an arbitrary dimensions

In [13]:
a2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a2[:,1]

array([2, 5, 8])

In [15]:
a2[0,0] = 99
a2

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

### `nparrays` can be reshaped 

In [18]:
a2 = np.arange(15).reshape(3,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
a2.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [20]:
np.dot(a2, a2.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

## Broadcasting

<img src="http://www.scipy-lectures.org/_images/numpy_broadcasting.png">

Standard sum:

In [39]:
a = np.array([0,0,0,10,10,10,20,20,20,30,30,30]).reshape(4,3)
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [40]:
b = np.tile([0,1,2],(4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [41]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

Broatcasting:

In [42]:
b = np.array([0,1,2])

In [43]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [52]:
a = np.array([0,10,20,30]).reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [54]:
b

array([0, 1, 2])

In [53]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])