# Numpy


*    Extension package to Python for multi-dimensional arrays
*    Closer to hardware (efficiency)
*    Designed for scientific computation (convenience)
*    Also known as array oriented computing

[More about arrays](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
a.shape

(4,)

In [10]:
a.dtype

dtype('int64')

In [13]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [2]:
a = np.arange(1000)

In [3]:
L = range(1000)

In [4]:
%timeit [i**2 for i in L]

255 µs ± 1.11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%timeit a**2

1.22 µs ± 8.82 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
%timeit sum(L)

16.2 µs ± 91.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%timeit np.sum(a)

2.31 µs ± 9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
np.array?

`nparrays` can have an arbitrary dimensions

In [65]:
a2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a2[:,1]

array([2, 5, 8])

In [67]:
a2[0,0] = 99
a2

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [68]:
a2 = np.arange(25).reshape(5,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
a2.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [74]:
np.dot(a2, a2.T)

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

## Broadcasting

<img src="http://www.scipy-lectures.org/_images/numpy_broadcasting.png">